---
# handlers file for ansible-nexus

- name: 'start nexus'
  sudo: yes
  systemd: name=nexus state=started
  tags:
    - init

- name: 'restart nexus'
  sudo: yes
  systemd: name=nexus state=restarted
